### ISSUE TITLE
can't compile the nms_kernel.cu.cc

### ISSUE THREAD

**Issue by zwyzwy** [traveller59/second.pytorch#6] opened 2018-10-12 09:55 UTC
I have met the problem while compile the "../cc/nms/nms_kernel.cu.cc", "../cc/nms/nms.cc"
the log output is below:

/usr/lib64/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
nvcc -std=c++14 -c -o ../cc/nms/nms_kernel.cu.o ../cc/nms/nms_kernel.cu.cc -I/usr/local/cuda/include -x cu -Xcompiler -fPIC -arch=sm_52 --expt-relaxed-constexpr
nvcc fatal   : Value 'c++14' is not defined for option 'std'
concurrent.futures.process._RemoteTraceback:
"""
Traceback (most recent call last):
  File "/mnt/data-3/data/wenyong.zheng/vxlnet/second.pytorch/second/core/non_max_suppression/nms_cpu.py", line 10, in <module>
    from second.core.non_max_suppression.nms import (
ModuleNotFoundError: No module named 'second.core.non_max_suppression.nms'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.6/concurrent/futures/process.py", line 175, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/usr/lib64/python3.6/concurrent/futures/process.py", line 153, in _process_chunk
    return [fn(*args) for args in chunk]
  File "/usr/lib64/python3.6/concurrent/futures/process.py", line 153, in <listcomp>
    return [fn(*args) for args in chunk]
  File "/mnt/data-3/data/wenyong.zheng/vxlnet/second.pytorch/second/utils/buildtools/command.py", line 256, in compile_func
    raise RuntimeError("compile failed with retcode", ret.returncode)
RuntimeError: ('compile failed with retcode', 1)
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "create_data.py", line 9, in <module>
    from second.core import box_np_ops
  File "/mnt/data-3/data/wenyong.zheng/vxlnet/second.pytorch/second/core/box_np_ops.py", line 7, in <module>
    from second.core.non_max_suppression.nms_gpu import rotate_iou_gpu_eval
  File "/mnt/data-3/data/wenyong.zheng/vxlnet/second.pytorch/second/core/non_max_suppression/__init__.py", line 1, in <module>
    from second.core.non_max_suppression.nms_cpu import nms_jit, soft_nms_jit
  File "/mnt/data-3/data/wenyong.zheng/vxlnet/second.pytorch/second/core/non_max_suppression/nms_cpu.py", line 18, in <module>
    cuda=True)
  File "/mnt/data-3/data/wenyong.zheng/vxlnet/second.pytorch/second/utils/buildtools/pybind11_build.py", line 113, in load_pb11
    cmds, cwd, num_workers=num_workers, compiler=compiler)
  File "/mnt/data-3/data/wenyong.zheng/vxlnet/second.pytorch/second/utils/buildtools/command.py", line 278, in compile_libraries
    if any([r.returncode != 0 for r in rets]):
  File "/mnt/data-3/data/wenyong.zheng/vxlnet/second.pytorch/second/utils/buildtools/command.py", line 278, in <listcomp>
    if any([r.returncode != 0 for r in rets]):
  File "/usr/lib64/python3.6/concurrent/futures/process.py", line 366, in _chain_from_iterable_of_lists
    for element in iterable:
  File "/usr/lib64/python3.6/concurrent/futures/_base.py", line 586, in result_iterator
    yield fs.pop().result()
  File "/usr/lib64/python3.6/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/usr/lib64/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
RuntimeError: ('compile failed with retcode', 1)

**Comment by traveller59** [comment] 2018-10-12 10:09
fixed in 24da331.

**Comment by traveller59** [comment] 2018-10-15 02:04
This seems that your boost is too old (or g++?). I can't reproduce this in Ubuntu 16.04 with boost 1.58, are you using 14.04?
you can uninstall boost and install newest boost by 
```
sudo add-apt-repository ppa:boost-latest/ppa
sudo apt-get update
sudo apt install libboost-all-dev
```

**Comment by zwyzwy** [comment] 2018-10-15 08:56
it seems another error as follows:
/usr/lib64/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
nvcc -std=c++11 -c -o ../cc/nms/nms_kernel.cu.o ../cc/nms/nms_kernel.cu.cc -I/usr/local/cuda/include -x cu -Xcompiler -fPIC -arch=sm_52 --expt-relaxed-constexpr
g++ -std=c++11 -shared -o /mnt/data-3/data/wenyong.zheng/vxlnet/second.pytorch/second/core/non_max_suppression/nms.so ../cc/nms/nms_kernel.cu.o ../cc/nms/nms.cc -I/usr/local/cuda/include -fPIC -O3 -L/usr/local/cuda/lib64 -lcublas -lcudart
In file included from ../cc/nms/nms.cc:1:0:
../cc/nms/nms.h:3:31: fatal error: pybind11/pybind11.h: No such file or directory
 #include <pybind11/pybind11.h>
                               ^
compilation terminated.
concurrent.futures.process._RemoteTraceback:
"""
Traceback (most recent call last):
  File "/mnt/data-3/data/wenyong.zheng/vxlnet/second.pytorch/second/core/non_max_suppression/nms_cpu.py", line 10, in <module>
    from second.core.non_max_suppression.nms import (
ModuleNotFoundError: No module named 'second.core.non_max_suppression.nms'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.6/concurrent/futures/process.py", line 175, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/usr/lib64/python3.6/concurrent/futures/process.py", line 153, in _process_chunk
    return [fn(*args) for args in chunk]
  File "/usr/lib64/python3.6/concurrent/futures/process.py", line 153, in <listcomp>
    return [fn(*args) for args in chunk]
  File "/mnt/data-3/data/wenyong.zheng/vxlnet/second.pytorch/second/utils/buildtools/command.py", line 256, in compile_func
    raise RuntimeError("compile failed with retcode", ret.returncode)
RuntimeError: ('compile failed with retcode', 1)
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "create_data.py", line 9, in <module>
    from second.core import box_np_ops
  File "/mnt/data-3/data/wenyong.zheng/vxlnet/second.pytorch/second/core/box_np_ops.py", line 7, in <module>
    from second.core.non_max_suppression.nms_gpu import rotate_iou_gpu_eval
  File "/mnt/data-3/data/wenyong.zheng/vxlnet/second.pytorch/second/core/non_max_suppression/__init__.py", line 1, in <module>
    from second.core.non_max_suppression.nms_cpu import nms_jit, soft_nms_jit
  File "/mnt/data-3/data/wenyong.zheng/vxlnet/second.pytorch/second/core/non_max_suppression/nms_cpu.py", line 18, in <module>
    cuda=True)
  File "/mnt/data-3/data/wenyong.zheng/vxlnet/second.pytorch/second/utils/buildtools/pybind11_build.py", line 113, in load_pb11
    cmds, cwd, num_workers=num_workers, compiler=compiler)
  File "/mnt/data-3/data/wenyong.zheng/vxlnet/second.pytorch/second/utils/buildtools/command.py", line 278, in compile_libraries
    if any([r.returncode != 0 for r in rets]):
  File "/mnt/data-3/data/wenyong.zheng/vxlnet/second.pytorch/second/utils/buildtools/command.py", line 278, in <listcomp>
    if any([r.returncode != 0 for r in rets]):
  File "/usr/lib64/python3.6/concurrent/futures/process.py", line 366, in _chain_from_iterable_of_lists
    for element in iterable:
  File "/usr/lib64/python3.6/concurrent/futures/_base.py", line 586, in result_iterator
    yield fs.pop().result()
  File "/usr/lib64/python3.6/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/usr/lib64/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
RuntimeError: ('compile failed with retcode', 1)

**Comment by traveller59** [comment] 2018-10-15 10:47
Where is your pybind11 library? run ```python3 -m pybind11 --includes```, if you see nothing, you need to install pybind11 to python3 environment.

**Comment by zwyzwy** [comment] 2018-10-15 11:30
I have no root to go "sudo apt install ..." , how can I update the libboost library?

**Comment by zwyzwy** [comment] 2018-10-15 17:39
another error occurred:
/usr/lib64/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "create_data.py", line 9, in <module>
    from second.core import box_np_ops
  File "/mnt/data-3/data/wenyong.zheng/vxlnet/second.pytorch/second/core/box_np_ops.py", line 7, in <module>
    from second.core.non_max_suppression.nms_gpu import rotate_iou_gpu_eval
  File "/mnt/data-3/data/wenyong.zheng/vxlnet/second.pytorch/second/core/non_max_suppression/__init__.py", line 2, in <module>
    from second.core.non_max_suppression.nms_gpu import nms_gpu, rotate_iou_gpu, rotate_nms_gpu
  File "/mnt/data-3/data/wenyong.zheng/vxlnet/second.pytorch/second/core/non_max_suppression/nms_gpu.py", line 36, in <module>
    @cuda.jit('(int64, float32, float32[:, :], uint64[:])')
  File "/home/users/wenyong.zheng/.local/lib/python3.6/site-packages/numba/cuda/decorators.py", line 96, in kernel_jit
    kernel.bind()
  File "/home/users/wenyong.zheng/.local/lib/python3.6/site-packages/numba/cuda/compiler.py", line 495, in bind
    self._func.get()
  File "/home/users/wenyong.zheng/.local/lib/python3.6/site-packages/numba/cuda/compiler.py", line 369, in get
    cuctx = get_context()
  File "/home/users/wenyong.zheng/.local/lib/python3.6/site-packages/numba/cuda/cudadrv/devices.py", line 194, in get_context
    return _runtime.get_or_create_context(devnum)
  File "/home/users/wenyong.zheng/.local/lib/python3.6/site-packages/numba/cuda/cudadrv/devices.py", line 162, in get_or_create_context
    return self.push_context(self.gpus[devnum])
  File "/home/users/wenyong.zheng/.local/lib/python3.6/site-packages/numba/cuda/cudadrv/devices.py", line 40, in __getitem__
    return self.lst[devnum]
  File "/home/users/wenyong.zheng/.local/lib/python3.6/site-packages/numba/cuda/cudadrv/devices.py", line 26, in __getattr__
    numdev = driver.get_device_count()
  File "/home/users/wenyong.zheng/.local/lib/python3.6/site-packages/numba/cuda/cudadrv/driver.py", line 334, in get_device_count
    self.cuDeviceGetCount(byref(count))
  File "/home/users/wenyong.zheng/.local/lib/python3.6/site-packages/numba/cuda/cudadrv/driver.py", line 272, in __getattr__
    self.initialization_error)
numba.cuda.cudadrv.error.CudaSupportError: Error at driver init:

Possible CUDA driver libraries are found but error occurred during load:
/usr/lib/libcuda.so: wrong ELF class: ELFCLASS32

**Comment by traveller59** [comment] 2018-10-16 01:40
I am not familiar with centOS, the following thing is just advises, I don't know whether they are working.
Are you using 32-bit system or using 32-bit cuda? If you are using 32-bit OS, please switch to 64bit. If you are using 32-bit cuda, consider uninstall cuda, install cuda by official .run file, or using Anaconda environment and using ```conda install -c anaconda cudatoolkit=x.x``` (8.0, 9.0, etc.) to install cuda for numba/pytorch in anaconda.

**Comment by zwyzwy** [comment] 2018-10-16 09:08
After I modify the parameter "NUMBAPRO_CUDA_DRIVER" to the right path of my 64-bit libcuda.so, it works.
Thank you very much !

**Closed** 2018-10-16 09:08 UTC
