### ISSUE TITLE
Unable train in ver 1.6 for assert failed.

### ISSUE THREAD

**Issue by EpsAvlc** [traveller59/second.pytorch#126] opened 2019-04-01 09:16 UTC
in RPNBase class there is a strange code line : 
```python
        for val in must_equal_list:
             assert val == must_equal_list[0]
```
and when i train, it assert failed.

i just comment out this line and every thing turned ok.

**Comment by EpsAvlc** [comment] 2019-04-01 09:27
added: I am training kitti dataset and in config file : upsample_strides: [1, 2]

**Comment by EpsAvlc** [comment] 2019-04-01 12:03
I also find that, in kittiviewer/backend/main.py.  
line 61
origin code 
```python
     dataset_class_name = instance["dataset_class_name"]
    BACKEND.dataset = get_dataset_class(dataset_class_name)
```

but the json received doesn't have dataset_class_name,
so I changed it into 
```
    # dataset_class_name = instance["dataset_class_name"]
    BACKEND.dataset = get_dataset_class("KittiDataset")
```
And it worked again.

**Comment by traveller59** [comment] 2019-04-01 13:47
RPN problem: should be fixed in newest commit. 
frontend problem: The frontend should send "dataset_class_name", I can't reproduce this.

**Comment by EpsAvlc** [comment] 2019-04-01 13:55
> RPN problem: should be fixed in newest commit.
> frontend problem: The frontend should send "dataset_class_name", I can't reproduce this.

I found the datasetClassName is hardcode into KittiViewer.js. Does it means that if i want to use my custom data, i should change it in the kittiViewer?(which doesn't be mentioned in release note).

**Comment by traveller59** [comment] 2019-04-01 14:16
see [this](https://github.com/traveller59/second.pytorch/blob/master/second/kittiviewer/frontend/index.html#L292). that variable will change when you change the dataset name in frontend. you may need to press enter after you input the dataset name.

**Comment by EpsAvlc** [comment] 2019-04-01 14:43
Ok, somehow my web didn't have datasetname panel and now it appeared...
Every thing worked.
Thank you for your patient.

**Closed** 2019-04-02 06:41 UTC
